services:
  meshcentral:
    build:
      context: https://github.com/jugurtha114/MeshCentral-jugu.git#feature/audio-stream
      dockerfile: docker/Dockerfile-debian
    container_name: meshcentral
    environment:
      - DYNAMIC_CONFIG=true
      - HOSTNAME=pc.aixofit.com
      - PORT=4443
      - REDIR_PORT=80
      - ALLOW_NEW_ACCOUNTS=true
    volumes:
      - meshcentral-data:/opt/meshcentral/meshcentral-data
      - meshcentral-files:/opt/meshcentral/meshcentral-files
      - meshcentral-web:/opt/meshcentral/meshcentral-web
      - meshcentral-backups:/opt/meshcentral/meshcentral-backups
    ports:
      - "4443:4443"
    restart: unless-stopped

volumes:
  meshcentral-data:
  meshcentral-files:
  meshcentral-web:
  meshcentral-backups:
